In [147]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [148]:
df =pd.read_csv('Vehicle_Accidents_in_Iowa_by_Location__Last_Ten_Years_.csv')

In [149]:
df.shape

(557185, 37)

In [150]:
df.head()

DOT Case Number Law Enforcement Case Number       Crash Date & Time  \
0       2011636263                     11-1528  06/28/2011 11:38:00 AM   
1       2011643409                   201101827  07/03/2011 09:43:00 PM   
2       2011641023                     11-0088  02/08/2011 07:00:00 PM   
3       2012684967                         NaN  05/04/2012 11:51:00 AM   
4       2011642449                         NaN  07/27/2011 06:10:00 AM   

   District   County        City Route Crash Month  Crash Day Crash Time  ...  \
0         1     POLK   URBANDALE   NaN        June    Tuesday      11:38  ...   
1         1    BOONE         NaN   NaN        July     Sunday      21:43  ...   
2         1  WEBSTER         NaN   NaN    February    Tuesday      19:00  ...   
3         6  JOHNSON   IOWA CITY  US 6         May     Friday      11:51  ...   
4         1     POLK  DES MOINES   NaN        July  Wednesday      06:10  ...   

  Fatalities Injuries Major Injuries Minor Injuries Possible Injuries  \
0          0        0              0              0                 0   
1          0        0              0              0                 0   
2          0        0              0              0                 0   
3          0        0              0              0                 0   
4          0        0              0              0                 0   

  Unknown Injuries Property Damage Report Type             Rest Update  \
0                0            6500       TraCS  08/14/2018 04:42:27 PM   
1                0            2000       TraCS  08/14/2018 04:42:27 PM   
2                0            2000       TraCS  08/14/2018 04:42:27 PM   
3                0            2599     Officer  08/14/2018 04:42:27 PM   
4                0            3100     Officer  08/14/2018 04:42:27 PM   

                                  Crash Location  
0   POINT (-93.73654589797147 41.62922672395549)  
1   POINT (-93.87429624122426 42.18527185276003)  
2   POINT (-94.12854269059548 42.46583138486093)  
3   POINT (-91.53210057297697 41.64546030234435)  
4  POINT (-93.62744704200334 41.586315087439765)  

[5 rows x 37 columns]

In [151]:
df.columns

Index(['DOT Case Number', 'Law Enforcement Case Number', 'Crash Date & Time',
       'District', 'County', 'City', 'Route', 'Crash Month', 'Crash Day',
       'Crash Time', 'Major Cause', 'Crash Manner', 'Crash Severity',
       'Surface Conditions', 'Drug/Alcohol Related', 'Environment', 'Roadway',
       'Light Conditions', 'Weather Conditions', 'Work Zone', 'Paved Road',
       'Roadway Junction', 'First Harmful Event', 'Harmful Event Location',
       'Literal Description', 'Vehicles', 'Occupants', 'Fatalities',
       'Injuries', 'Major Injuries', 'Minor Injuries', 'Possible Injuries',
       'Unknown Injuries', 'Property Damage', 'Report Type', 'Rest Update',
       'Crash Location'],
      dtype='object')

In [152]:
df['Roadway Junction'].sample(20)

119890    Non-intersection:  Non-junction/no special fea...
125185                 Intersection:  Four-way intersection
348497                 Intersection:  Four-way intersection
41663     Intersection:  Other intersection (explain in ...
221560    Non-intersection:  Non-junction/no special fea...
84769                         Intersection:  T-intersection
15040     Non-intersection:  Other non-intersection (exp...
320169                 Intersection:  Four-way intersection
238323                 Intersection:  Four-way intersection
275568          Non-intersection:  Driveway access (within)
523167    Non-intersection:  Non-junction/no special fea...
456513                 Intersection:  Four-way intersection
117367                 Intersection:  Four-way intersection
252113    Non-intersection:  Non-junction/no special fea...
503365    Non-intersection:  Non-junction/no special fea...
26293     Non-intersection:  Non-junction/no special fea...
333793                 Intersection:  Fo

In [153]:
df['Work Zone'].isnull().sum()

550459

Nearly the entirety of the 'Work Zone' column are missing values. Consider dropping.

In [154]:
df['Route'].isnull().sum()

330681

Less than half of the values are missing, but unsure how I would be able to fill missing values. Consider dropping.

In [155]:
df['Crash Day'].isnull().sum()

0

In [156]:
df['Major Cause'].nunique()

71

In [157]:
df['Crash Manner'].unique()

array(['Angle, oncoming left turn', 'Not Reported',
       'Rear-end (front to rear)', 'Broadside (front to side)',
       'Non-collision (single vehicle)', 'Sideswipe, same direction',
       'Head-on (front to front)', 'Unknown',
       'Sideswipe, opposite direction', 'Other (explain in narrative)',
       'Rear to side', 'Rear to rear'], dtype=object)

In [158]:
df['Crash Severity'].isnull().sum()
df['Crash Severity'].unique()

array(['Property Damage Only', 'Possible/Unknown', 'Major Injury',
       'Minor Injury', 'Fatal'], dtype=object)

In [159]:
df['Surface Conditions'].unique()

array(['Dry', 'Not Reported', 'Mud, dirt', 'Wet', 'Ice/frost', 'Slush',
       'Snow', 'Other (explain in narrative)',
       'Water (standing or moving)', 'Unknown', 'Gravel', 'Sand', 'Oil'],
      dtype=object)

In [160]:
df['Drug/Alcohol Related'].unique()

array(['None Indicated', 'Alcohol (Statutory)',
       'Drug/Alcohol (Statutory)', 'Drug', 'Refused',
       'Under Influence of Alcohol/Drugs/Medications',
       'Alcohol (< Statutory)', 'Drug/Alcohol (< Statutory)'],
      dtype=object)

In [161]:
df['Environment'].unique()

array(['Other (explain in narrative)', 'Not Reported', 'None apparent',
       'Weather conditions', 'Visual obstruction', 'Animal in roadway',
       'Unknown', 'Glare', 'Non-motorist action', 'Severe crosswind'],
      dtype=object)

In [162]:
df['Roadway'].unique()

array(['None apparent', 'Not Reported',
       'Surface condition (e.g.wet, icy)', 'Work Zone (roadway-related)',
       'Other (explain in narrative)', 'Non-highway work', 'Debris',
       'Ruts/holes/bumps', 'Unknown', 'Shoulders (none, low, soft, high)',
       'Traffic control obscured', 'Obstruction in roadway',
       'Slippery, loose or worn surface', 'Traffic backup, prior crash',
       'Traffic backup, regular congestion',
       'Traffic backup, prior non-recurring incident', 'Disabled vehicle'],
      dtype=object)

In [163]:
df['Weather Conditions'].unique()

array(['Clear', 'Not Reported', 'Cloudy', 'Rain', 'Snow',
       'Blowing sand, soil, dirt', 'Sleet, hail', 'Unknown',
       'Fog, smoke, smog', 'Severe Winds', 'Other (explain in narrative)',
       'Blowing Snow', 'Freezing rain/drizzle'], dtype=object)

In [164]:
df['Weather Conditions'].isna().sum()

0

In [165]:
df['Paved Road'].unique()

array(['Paved', 'Unpaved', '0', '9'], dtype=object)

In [166]:
df['Roadway Junction'].nunique()

26

In [167]:
df['First Harmful Event'].unique()

array(['Collision with:  Vehicle in traffic', 'Collision with:  Animal',
       'Non-collision events:  Overturn/rollover',
       'Collision with fixed object:  Ditch',
       'Collision with:  Parked motor vehicle',
       'Non-collision events:  Other non-collision (explain in narrative)',
       'Collision with fixed object:  Utility pole/light support',
       'Collision with:  Non-motorist (see non-motorist section - NOT a unit)',
       'Collision with fixed object:  Tree',
       'Collision with fixed object:  Curb/island/raised median',
       'Collision with:  Other non-fixed object (explain in narrative)',
       'Collision with fixed object:  Guardrail - face',
       'Collision with fixed object:  Other fixed object (explain in narrative)',
       'Collision with fixed object:  Culvert/pipe opening',
       'Not Reported',
       'Collision with fixed object:  Bridge overhead structure',
       'Collision with fixed object:  Traffic sign support',
       'Collision with fi

In [168]:
df['Harmful Event Location'].unique()

array(['On Roadway', 'Not Reported.', '7', 'Roadside', 'Shoulder',
       'Outside trafficway', '99', 'Gore', 'Median', '8', '98', 'Unknown'],
      dtype=object)

In [169]:
(df['Vehicles']==2).sum()

331088

In [170]:
(df['Occupants']==1).sum()

170203

In [171]:
print(type(df['Occupants'][1]))
print(type(df['Vehicles'][1]))

<class 'numpy.int64'>
<class 'numpy.int64'>


In [172]:
(df['Fatalities']==0).sum()

553864

In [173]:
print(df['Injuries'].isna().sum())
df['Injuries'].unique()

0


array([ 0,  1,  2,  3,  5,  4,  7, 13,  6,  9, 16, 11, 22, 14,  8, 21, 10,
       12, 38, 26, 35, 15, 25, 32, 34, 30])

In [174]:
df['Major Injuries'].unique()

array([ 0,  1,  2,  3,  4,  5,  7,  6, 10])

In [176]:
df['Minor Injuries'].unique()

array([ 0,  1,  2,  3,  4,  5,  6, 22,  8,  7, 12, 10,  9, 11, 34, 38, 20,
       33])

In [177]:
(df['Injuries']==0).sum()

404449

More than half of the accidents have no injuries.

Dropping 'Minor Injuries' 'Major Injuries' 'Possible Injuries' 'Unknown Injuries'. Leaving only sum: 'Injuries'

In [178]:
df.columns

Index(['DOT Case Number', 'Law Enforcement Case Number', 'Crash Date & Time',
       'District', 'County', 'City', 'Route', 'Crash Month', 'Crash Day',
       'Crash Time', 'Major Cause', 'Crash Manner', 'Crash Severity',
       'Surface Conditions', 'Drug/Alcohol Related', 'Environment', 'Roadway',
       'Light Conditions', 'Weather Conditions', 'Work Zone', 'Paved Road',
       'Roadway Junction', 'First Harmful Event', 'Harmful Event Location',
       'Literal Description', 'Vehicles', 'Occupants', 'Fatalities',
       'Injuries', 'Major Injuries', 'Minor Injuries', 'Possible Injuries',
       'Unknown Injuries', 'Property Damage', 'Report Type', 'Rest Update',
       'Crash Location'],
      dtype='object')

In [179]:
(df['Property Damage']==0).sum()

5487

Dropping non-relevant columns

In [180]:
df.drop(['DOT Case Number', 'Law Enforcement Case Number', 'Work Zone', 'Route', 'Literal Description', 'Harmful Event Location', 'Report Type', 'Rest Update', 'Minor Injuries', 'Major Injuries', 'Possible Injuries', 'Unknown Injuries'],axis=1, inplace=True)

In [184]:
df.columns

Index(['Crash Date & Time', 'District', 'County', 'City', 'Crash Month',
       'Crash Day', 'Crash Time', 'Major Cause', 'Crash Manner',
       'Crash Severity', 'Surface Conditions', 'Drug/Alcohol Related',
       'Environment', 'Roadway', 'Light Conditions', 'Weather Conditions',
       'Paved Road', 'Roadway Junction', 'First Harmful Event', 'Vehicles',
       'Occupants', 'Fatalities', 'Injuries', 'Property Damage',
       'Crash Location'],
      dtype='object')

In [185]:
df.head()

Crash Date & Time  District   County        City Crash Month  \
0  06/28/2011 11:38:00 AM         1     POLK   URBANDALE        June   
1  07/03/2011 09:43:00 PM         1    BOONE         NaN        July   
2  02/08/2011 07:00:00 PM         1  WEBSTER         NaN    February   
3  05/04/2012 11:51:00 AM         6  JOHNSON   IOWA CITY         May   
4  07/27/2011 06:10:00 AM         1     POLK  DES MOINES        July   

   Crash Day Crash Time                            Major Cause  \
0    Tuesday      11:38         Crossed centerline (undivided)   
1     Sunday      21:43                                 Animal   
2    Tuesday      19:00                                 Animal   
3     Friday      11:51  FTYROW:  Other (explain in narrative)   
4  Wednesday      06:10                                Unknown   

                Crash Manner        Crash Severity  ... Weather Conditions  \
0  Angle, oncoming left turn  Property Damage Only  ...              Clear   
1               Not Reported  Property Damage Only  ...       Not Reported   
2               Not Reported  Property Damage Only  ...       Not Reported   
3   Rear-end (front to rear)  Property Damage Only  ...              Clear   
4  Broadside (front to side)  Property Damage Only  ...             Cloudy   

  Paved Road                                   Roadway Junction  \
0      Paved               Intersection:  Four-way intersection   
1      Paved                                       Not Reported   
2      Paved                                       Not Reported   
3      Paved  Non-intersection:  Non-junction/no special fea...   
4      Paved               Intersection:  Four-way intersection   

                   First Harmful Event Vehicles Occupants Fatalities Injuries  \
0  Collision with:  Vehicle in traffic        2         3          0        0   
1              Collision with:  Animal        1         1          0        0   
2              Collision with:  Animal        1         1          0        0   
3  Collision with:  Vehicle in traffic        3         3          0        0   
4  Collision with:  Vehicle in traffic        2         2          0        0   

  Property Damage                                 Crash Location  
0            6500   POINT (-93.73654589797147 41.62922672395549)  
1            2000   POINT (-93.87429624122426 42.18527185276003)  
2            2000   POINT (-94.12854269059548 42.46583138486093)  
3            2599   POINT (-91.53210057297697 41.64546030234435)  
4            3100  POINT (-93.62744704200334 41.586315087439765)  

[5 rows x 25 columns]

In [186]:
df['Crash Date'] = df['Crash Date & Time'].str[:10]

In [187]:
df['Crash Date'].head()

0    06/28/2011
1    07/03/2011
2    02/08/2011
3    05/04/2012
4    07/27/2011
Name: Crash Date, dtype: object

In [188]:
df.drop(['Crash Date & Time'], axis =1, inplace = True)

In [189]:
df.columns

Index(['District', 'County', 'City', 'Crash Month', 'Crash Day', 'Crash Time',
       'Major Cause', 'Crash Manner', 'Crash Severity', 'Surface Conditions',
       'Drug/Alcohol Related', 'Environment', 'Roadway', 'Light Conditions',
       'Weather Conditions', 'Paved Road', 'Roadway Junction',
       'First Harmful Event', 'Vehicles', 'Occupants', 'Fatalities',
       'Injuries', 'Property Damage', 'Crash Location', 'Crash Date'],
      dtype='object')

In [196]:
duplicateRowsDF = df.duplicated()
duplicateRowsDF

0         False
1         False
2         False
3         False
4         False
          ...  
557180    False
557181    False
557182    False
557183    False
557184    False
Length: 557129, dtype: bool

In [197]:
df.shape

(557129, 25)

Drop duplicates

In [195]:
df.drop_duplicates(subset=None, keep='first', inplace=True)

In [59]:
#print((df['Crash Date & Time'].str.len() !=10) == True)

In [58]:
#df['Crash Date'] = pd.to_datetime(df['Crash Date & Time'], format = '%m/%d/%y')